/**
 * Local Storage Data Models
 * 
 * This file defines all data interfaces and storage utilities for the finance app.
 * All data is stored locally in the browser's localStorage for privacy.
 */

/**
 * Account Interface
 * Represents a bank account or investment account
 */
export interface Account {
  id: string;
  name: string;
  type: 'bank' | 'investment'; // Account classification
  balance: number;
  currency: string; // ISO currency code (USD, EUR, etc.)
  color: string; // Hex color for visual identification
}

/**
 * Asset Interface
 * Represents physical or financial assets (property, vehicles, equipment)
 * Can have linked income and expenses to track profitability
 */
export interface Asset {
  id: string;
  name: string;
  type: 'property' | 'vehicle' | 'equipment' | 'other';
  purchaseValue: number;
  currentValue: number;
  currency: string;
  purchaseDate: string; // ISO date format
  description?: string;
  color: string; // Hex color for visual identification
}

/**
 * Income Stream Interface
 * Represents any source of income
 * 
 * Note: frequency field handles recurrence (weekly, monthly, yearly, etc.)
 * No separate "type" field needed - frequency already indicates if it's recurring
 */
export interface IncomeStream {
  id: string;
  source: string; // Name/description of income source
  amount: number;
  currency: string;
  frequency: string; // weekly | biweekly | monthly | quarterly | yearly
  accountId: string; // Which account receives this income
  category: string; // Employment, Business, Investments, etc.
  assetId?: string; // Optional: link to asset if income is generated by an asset
}

/**
 * Expense Interface
 * Represents any expense or bill
 * 
 * Note: frequency field handles recurrence (weekly, monthly, yearly, etc.)
 * No separate "type" field needed - frequency already indicates if it's recurring
 */
export interface Expense {
  id: string;
  name: string;
  amount: number;
  currency: string;
  category: string; // Housing, Transportation, Family, Business, Others
  subcategory: string; // More specific categorization
  frequency: string; // weekly | biweekly | monthly | quarterly | yearly
  accountId: string; // Which account this expense is paid from
  assetId?: string; // Optional: link to asset if expense is related to an asset
}

/**
 * Goal Interface
 * Represents financial savings goals
 */
export interface Goal {
  id: string;
  name: string;
  targetAmount: number;
  currentAmount: number;
  deadline: string; // ISO date format
  accountId: string; // Which account is used for this goal
  priority: 'high' | 'medium' | 'low';
}

/**
 * User Profile Interface
 * Stores user preferences and onboarding status
 */
export interface UserProfile {
  name: string;
  email: string;
  currency: string; // Default/base currency for the user
  hasCompletedOnboarding: boolean;
  avatar?: string; // Base64 image or URL
  phone?: string;
  location?: string;
  bio?: string;
}

/**
 * User Preferences Interface
 * Stores UI preferences like theme
 */
export interface UserPreferences {
  isDarkMode: boolean;
}

/**
 * localStorage Keys
 * All data is prefixed with 'financeflow_' to avoid conflicts
 */
const STORAGE_KEYS = {
  ACCOUNTS: 'financeflow_accounts',
  ASSETS: 'financeflow_assets',
  INCOME: 'financeflow_income',
  EXPENSES: 'financeflow_expenses',
  GOALS: 'financeflow_goals',
  PROFILE: 'financeflow_profile',
  PREFERENCES: 'financeflow_preferences',
};

/**
 * Storage Utilities
 * Handles all localStorage operations for the app
 */
function get<T>(key: string, fallback: T): T {
  const data = localStorage.getItem(key);
  return data ? JSON.parse(data) : fallback;
}

function set(key: string, value: unknown) {
  localStorage.setItem(key, JSON.stringify(value));
}

export const storage = {
  getAccounts: () => get<Account[]>(STORAGE_KEYS.ACCOUNTS, []),
  setAccounts: (accounts: Account[]) => set(STORAGE_KEYS.ACCOUNTS, accounts),
  getAssets: () => get<Asset[]>(STORAGE_KEYS.ASSETS, []),
  setAssets: (assets: Asset[]) => set(STORAGE_KEYS.ASSETS, assets),
  getIncome: () => get<IncomeStream[]>(STORAGE_KEYS.INCOME, []),
  setIncome: (income: IncomeStream[]) => set(STORAGE_KEYS.INCOME, income),
  getExpenses: () => get<Expense[]>(STORAGE_KEYS.EXPENSES, []),
  setExpenses: (expenses: Expense[]) => set(STORAGE_KEYS.EXPENSES, expenses),
  getGoals: () => get<Goal[]>(STORAGE_KEYS.GOALS, []),
  setGoals: (goals: Goal[]) => set(STORAGE_KEYS.GOALS, goals),
  getProfile: () => get<UserProfile | null>(STORAGE_KEYS.PROFILE, null),
  setProfile: (profile: UserProfile) => set(STORAGE_KEYS.PROFILE, profile),
  getPreferences: () => get<UserPreferences>(STORAGE_KEYS.PREFERENCES, { isDarkMode: false }),
  setPreferences: (preferences: UserPreferences) => set(STORAGE_KEYS.PREFERENCES, preferences),

  // Clear all data
  clearAll: () => {
    Object.values(STORAGE_KEYS).forEach(key => localStorage.removeItem(key));
  }
};
